config/routes.rb
ArtfulCommons::Application.routes.draw do
  resources :comments
  resources :users
  resources :artists
  resources :works
  resources :locations

  root :to => "Locations#index"

end

app/models/location.rb
class Location < ActiveRecord::Base

	has_many :works

end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController
  # GET /locations
  # GET /locations.xml
  def index
    @locations = Location.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @locations }
    end
  end

  # GET /locations/1
  # GET /locations/1.xml
  def show
    @location = Location.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/new
  # GET /locations/new.xml
  def new
    @location = Location.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @location }
    end
  end

  # GET /locations/1/edit
  def edit
    @location = Location.find(params[:id])
  end

  # POST /locations
  # POST /locations.xml
  def create
    @location = Location.new(params[:location])

    respond_to do |format|
      if @location.save
        format.html { redirect_to(root_path, :notice => 'Location was successfully created.') }
        format.xml  { render :xml => @location, :status => :created, :location => @location }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /locations/1
  # PUT /locations/1.xml
  def update
    @location = Location.find(params[:id])

    respond_to do |format|
      if @location.update_attributes(params[:location])
        format.html { redirect_to(@location, :notice => 'Location was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @location.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /locations/1
  # DELETE /locations/1.xml
  def destroy
    @location = Location.find(params[:id])
    @location.destroy

    respond_to do |format|
      format.html { redirect_to(locations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/locations_helper.rb
module LocationsHelper
end

app/views/locations/_form.html.erb
<%= form_for(@location) do |f| %>
  <% if @location.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@location.errors.count, "error") %> prohibited this location from being saved:</h2>

      <ul>
      <% @location.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Latitude" %><br />
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label "Longitude" %><br />
    <%= f.text_field :lng %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.text_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :is_active %><br />
    <%= f.check_box :is_active %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/locations/edit.html.erb
<h1>Editing location</h1>

<%= render 'form' %>

<%= link_to 'Show', @location %> |
<%= link_to 'Back', locations_path %>

app/views/locations/index.html.erb
<script type="text/javascript"
  src="http://maps.google.com/maps/api/js?sensor=false">
</script>
<script type="text/javascript">
function initialize() {
	var latlng = new google.maps.LatLng(42.353787, -71.066437);
	var myOptions = {
		zoom: 14,
		center: latlng,
		mapTypeId: google.maps.MapTypeId.ROADMAP
	};
	var map = new google.maps.Map(document.getElementById("map_canvas"), myOptions);
	<% i = 0 %>
	<% @locations.each do |location| %>
		<% if location.is_active %>
			var latlng<%= i %> = new google.maps.LatLng(<%= location.lat %>, <%= location.lng %>);
			var title<%=i%> =  '<%= location.title %>';
			var content<%=i%> = '<h2><%= location.title %></h2>'+
				'<p> proposed by:'+
				'<%=User.find_by_id(location.user_id).username %></p>'+
				'<h3>Current Works:</h3> <ul>'+
				<% location.works.each do |work| %>
					'<li><%= link_to work.title, work %> </li>'+
				<% end %>
				'</ul>'+
				'<%= link_to "Propose a new work at this location", new_work_path%>';
			var info<%=i%> = new google.maps.InfoWindow({
				content: content<%=i%>});
			var marker<%= i %> = new google.maps.Marker({
				position: latlng<%= i %>,
				map: map,
				title: title<%= i %>
			});
			google.maps.event.addListener(marker<%=i%>, 'click', function() {
				info<%=i%>.open(map, marker<%=i%>)});
			<% i = i + 1  %>
			<% end %>
	<% end %>
}
</script>
<div id="map_canvas"> </div>

<%= link_to 'New Location', new_location_path %>

<!-- <h1>Listing locations</h1>

<table>
  <tr>
    <th>X coord</th>
    <th>Y coord</th>
    <th>Description</th>
    <th>User</th>
    <th>Is active</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @locations.each do |location| %>
  <tr>
    <td><%= location.lat %></td>
    <td><%= location.lng %></td>
    <td><%= location.title %></td>
    <td><%= location.user_id %></td>
    <td><%= location.is_active %></td>
    <td><%= link_to 'Show', location %></td>
    <td><%= link_to 'Edit', edit_location_path(location) %></td>
    <td><%= link_to 'Destroy', location, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br /> -->

app/views/locations/new.html.erb
<h1>New location</h1>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/locations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Latitude:</b>
  <%= @location.lat %>
</p>

<p>
  <b>Longitude:</b>
  <%= @location.lng %>
</p>

<p>
  <b>Title:</b>
  <%= @location.title %>
</p>

<p>
  <b>User:</b>
  <%= @location.user_id %>
</p>

<p>
  <b>Is active:</b>
  <%= @location.is_active %>
</p>

<%= link_to 'Edit', edit_location_path(@location) %> |
<%= link_to 'Back', locations_path %>